### ISSUE TITLE
DeprecationWarning: Invalid 'main' field in '/app/package.json' of 'build/index.js'.

### ISSUE THREAD

**Issue by Traction6131** [sys-256/boiurl#7]
Hello there good sir 🙂 
In my quite professional production environment of your software, I have recently encountered an error. It seems to not affect my clients, however it isn't nice to see.
The error logs of my cocker container look like this:
```
boiurl  | (node:1) [DEP0128] DeprecationWarning: Invalid 'main' field in '/app/package.json' of 'build/index.js'. Please either fix that or report it to the module author
boiurl  | (Use `node --trace-deprecation ...` to show where the warning was created)
boiurl  | Server started on port 8035.
```
Running `node --trace-deprecation ...`:
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/app/...'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v17.9.0
``` 
My `docker-compose.yml` file looks like this:
```
version: "3"
services:
  boiurl:
    container_name: boiurl
    image: sys256/boiurl:latest
    volumes:
        - ./boi-data:/data
    restart: always
networks:
  default:
    name: nginx
    external: true
``` 
It probably is quite easy to fix, but I'm not sure how. Thanks for your response, and have a great holiday season 🎄 😃 🇹🇩 

P.S: when blockchain on the edge intergration with the sircoin federation protocol????
